language: node_js
node_js:
  - 14
before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://nirnaor:${GITHUB_TOKEN}@github.com/nirnaor/publish-test.git" > /dev/null 2>&1
  - git checkout master
deploy:
  provider: script
  script: "npm run releaseAfterMerge"
  skip_cleanup: true
  on:
    branch: master
