name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.1]
    steps:
      - uses: actions/checkout@master
        # with:
        #   name: wix-private/photography-pro-gallery
        #   ref: refs/heads/master
      - run: |
          git clone https://${NIRNAOR_PAT}@github.com/wix-private/photography-pro-gallery.git
          yarn config set @wix:registry https://npm.dev.wixpress.com
          ls
          cd photography-pro-gallery
          ls
          pwd
          node create-pr.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NIRNAOR_PAT: ${{ secrets.NIRNAOR_PAT }}
