name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Install and run lint
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Install, build, configure git and lerna publish
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
