name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Install, build, configure git and lerna publish
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm run build --if-present
    - run: git config --global user.email "octocat@github.com"
    - run: git config --global user.name "GitHub Actions"
    - run: git remote set-url origin https://wix@github.com/wix/pro-gallery
    - run: |
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

